export const dataColumn = [
  { year: "2010", population: 2 },
  { year: "2011", population: 3 },
  { year: "2012", population: 8 },
  { year: "2013", population: 9 },
  { year: "2014", population: 10 },
  { year: "2015", population: 11 },
  { year: "2016", population: 6 },
];

export const dataPie = [
  { region: "Laptop", val: 100 },
  { region: "PC", val: 120 },
  { region: "PK", val: 130 },
  { region: "Loa", val: 140 },
  { region: "Storage", val: 300 },
  { region: "Game", val: 180 },
];
export const energyConsumption = [
  {
    country: "2016",
    hydro: 30,
    oil: 15,
  },
  {
    country: "2015",
    hydro: 19,
    oil: 33,
  },
  {
    country: "2014",
    hydro: 10,
    oil: 20,
  },
  {
    country: "2013",
    hydro: 31,
    oil: 43,
  },
  {
    country: "2012",
    hydro: 23,
    oil: 30,
  },
  {
    country: "2011",
    hydro: 26,
    oil: 22,
  },
  {
    country: "2010",
    hydro: 35,
    oil: 31,
  },
];

export const dataOrder = [
  {
    id: "5eaf95dd",
    date: "6/13/2099",
    name: "Della Hamptonasd",
    nv: "Lois Graham",
  },
  {
    id: "b5d00ee1",
    date: "5/1/2099",
    name: "Mario Nealqwe",
    nv: "Walter Gibson",
  },
  {
    nv: "Leona Jefferson",
    id: "46667d8a",
    date: "1/23/2057",
    name: "Justin Blackqwe",
  },
];

export const dataLaptop = [
  { id: 1, specificationName: "Loại card đồ họa", specificationValue: "" },
  { id: 2, specificationName: "Loại CPU", specificationValue: "" },
  { id: 3, specificationName: "Dung lượng RAM", specificationValue: "" },
  { id: 4, specificationName: "Loại RAM", specificationValue: "" },
  { id: 5, specificationName: "Số khe ram", specificationValue: "" },
  { id: 6, specificationName: "Ổ cứng", specificationValue: "" },
  { id: 7, specificationName: "Màn hình cảm ứng", specificationValue: "" },
  { id: 8, specificationName: "Chất liệu tấm nền", specificationValue: "" },
  { id: 9, specificationName: "Tần số quét", specificationValue: "" },
  { id: 10, specificationName: "Kích thước màn hình", specificationValue: "" },
  { id: 11, specificationName: "Công nghệ màn hình", specificationValue: "" },
  {
    id: 12,
    specificationName: "Độ phân giải màn hình",
    specificationValue: "",
  },
  { id: 13, specificationName: "Loại đèn bàn phím", specificationValue: "" },
  { id: 14, specificationName: "Webcam", specificationValue: "" },
  { id: 15, specificationName: "Hệ điều hành", specificationValue: "" },
  { id: 16, specificationName: "Wi-Fi", specificationValue: "" },
  { id: 17, specificationName: "Bluetooth", specificationValue: "" },
  { id: 18, specificationName: "Công nghệ âm thanh", specificationValue: "" },
  { id: 19, specificationName: "Bảo mật", specificationValue: "" },
  { id: 20, specificationName: "Tính năng đặc biệt", specificationValue: "" },
  { id: 21, specificationName: "Pin", specificationValue: "" },
  { id: 22, specificationName: "Kích thước", specificationValue: "" },
  { id: 23, specificationName: "Trọng lượng", specificationValue: "" },
  { id: 24, specificationName: "Cổng giao tiếp", specificationValue: "" },
];
export const dataPhone = [
  { id: 1, specificationName: "Kích thước màn hình", specificationValue: "" },
  { id: 2, specificationName: "Công nghệ màn hình", specificationValue: "" },
  { id: 3, specificationName: "Độ phân giải màn hình", specificationValue: "" },
  { id: 4, specificationName: "Tính năng màn hình", specificationValue: "" },
  { id: 5, specificationName: "Tần số quét", specificationValue: "" },
  { id: 6, specificationName: "Kiểu màn hình", specificationValue: "" },
  { id: 7, specificationName: "Camera sau", specificationValue: "" },
  { id: 8, specificationName: "Quay video", specificationValue: "" },
  { id: 9, specificationName: "Tính năng camera", specificationValue: "" },
  { id: 10, specificationName: "Camera trước", specificationValue: "" },
  { id: 11, specificationName: "Quay video trước", specificationValue: "" },
  { id: 12, specificationName: "Chipset", specificationValue: "" },
  { id: 13, specificationName: "Loại CPU", specificationValue: "" },
  { id: 14, specificationName: "GPU", specificationValue: "" },
  { id: 15, specificationName: "Dung lượng RAM", specificationValue: "" },
  { id: 16, specificationName: "Bộ nhớ trong", specificationValue: "" },
  { id: 17, specificationName: "Khe cắm thẻ nhớ", specificationValue: "" },
  { id: 18, specificationName: "Pin", specificationValue: "" },
  { id: 19, specificationName: "Công nghệ sạc", specificationValue: "" },
  { id: 20, specificationName: "Cổng sạc", specificationValue: "" },
  { id: 21, specificationName: "Thẻ SIM", specificationValue: "" },
  { id: 22, specificationName: "Hệ điều hành", specificationValue: "" },
  { id: 23, specificationName: "Công nghệ NFC", specificationValue: "" },
  { id: 24, specificationName: "Hỗ trợ mạng", specificationValue: "" },
  { id: 25, specificationName: "Wi-Fi", specificationValue: "" },
  { id: 26, specificationName: "Bluetooth", specificationValue: "" },
  { id: 27, specificationName: "GPS", specificationValue: "" },
  { id: 28, specificationName: "Kích thước", specificationValue: "" },
  { id: 29, specificationName: "Trọng lượng", specificationValue: "" },
  { id: 30, specificationName: "Chất liệu mặt lưng", specificationValue: "" },
  { id: 31, specificationName: "Chất liệu khung viền", specificationValue: "" },
  {
    id: 32,
    specificationName: "Chỉ số kháng nước, bụi",
    specificationValue: "",
  },
  { id: 33, specificationName: "Tiện ích khác", specificationValue: "" },
  { id: 34, specificationName: "Công nghệ âm thanh", specificationValue: "" },
  { id: 35, specificationName: "Cảm biến vân tay", specificationValue: "" },
  { id: 36, specificationName: "Các loại cảm biến", specificationValue: "" },
  { id: 37, specificationName: "Tính năng đặc biệt", specificationValue: "" },
  { id: 38, specificationName: "Thời điểm ra mắt", specificationValue: "" },
];
